name: Hello World

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    permissions:
      contents: read              # <--- ADDED: Needed by actions/checkout
      actions: read             # using $GITHUB_OUTPUT
      id-token: write           # Necessary to create attestations
      attestations: write       # Necessary to push attestations to GH account
    env:
      JF_URL: ${{ vars.JF_URL }}
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - name: Push To Artifactory
        id: build
        env:
          ARTIFACT_PATH: "dev-generic-local/github-example/readme.md"
          FILE_NAME: "artifact.txt"
          JF_REPO_KEY: "dev-generic-local"
          TARGET_PATH_IN_REPO: "runs/${{ github.run_number }}/${{ env.FILE_NAME }}"
        run: |
          
          echo "Uploading ${{ env.FILE_NAME }} to ${{ env.JF_REPO_KEY }}/${{ env.TARGET_PATH_IN_REPO }}"
          jf rt u ${{ env.FILE_NAME }} ${{ env.JF_REPO_KEY }}/${{ env.TARGET_PATH_IN_REPO }} --detailed-summary | tee upload-summary.json

          # Extract SHA256 digest
          SHA256_DIGEST=$(jq -r '.files[0].sha256' upload-summary.json)
          ARTIFACTORY_SUBJECT_NAME="${{ env.JF_REPO_KEY }}/${{ env.TARGET_PATH_IN_REPO }}"

          # Storing outputs for later use
          echo "artifact_digest=$SHA256_DIGEST" >> $GITHUB_OUTPUT
          echo "artifactory_subject_name=$ARTIFACTORY_SUBJECT_NAME" >> $GITHUB_OUTPUT
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Create build-provenance attestation
        id: attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ steps.build.outputs.artifactory_subject_name }}
          subject-digest: sha256:${{ steps.build.outputs.artifact_digest }}
