name: Hello World

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
#    runs-on: self-hosted
    permissions:
      contents: read              # <--- ADDED: Needed by actions/checkout
      actions: read             # using $GITHUB_OUTPUT
      id-token: write           # Necessary to create attestations
      attestations: write       # Necessary to push attestations to GH account
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://635726ee2cd1.ngrok-free.app
        with:
          oidc-provider-name: providerowtd
      - name: Push To Artifactory
        id: build
        env:
          FILE_NAME: "artifact.txt"
          JF_REPO_KEY: "dev"
          TARGET_PATH_IN_REPO: "runs/${{ github.run_number }}"
        run: |
          
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "This is a test artifact created at $TIMESTAMP" >> ${{ env.FILE_NAME }}
          
          TARGET_NAME=${{ env.JF_REPO_KEY }}/${{ env.TARGET_PATH_IN_REPO }}/${{ env.FILE_NAME }}
          
          echo "Uploading ${{ env.FILE_NAME }} to $TARGET_NAME"
          jf rt u ${{ env.FILE_NAME }} $TARGET_NAME --detailed-summary | tee upload-summary.json

          # Extract SHA256 digest
          SHA256_DIGEST=$(jq -r '.files[0].sha256' upload-summary.json)

          echo "artifact_digest=$SHA256_DIGEST" >> $GITHUB_OUTPUT
          echo "artifact_subject_name=$TARGET_NAME" >> $GITHUB_OUTPUT
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Create build-provenance attestation
        id: attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ steps.build.outputs.artifact_subject_name }}
          subject-digest: sha256:${{ steps.build.outputs.artifact_digest }}
