name: Docker Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    permissions:
      contents: read            # Necessary by actions/checkout
      actions: read             # using $GITHUB_OUTPUT
      id-token: write           # Necessary to create attestations
      attestations: write       # Necessary to push attestations to GH account

    env:
      OIDC_PROVIDER_NAME: swampup-2025/testing-githubcentral-jpd-public@github
      JF_URL: ${{ vars.JF_URL }}            # e.g: https://githubcentral.jfrog.io/
      # JF_REGISTRY: ${{ vars.JF_REGISTRY }}  # e.g: githubcentral.jfrog.io/dev-docker
      JF_REGISTRY: githubcentral.jfrog.io/dev-docker-local
      JF_DOCKER_REPO: dev-docker-local
      IMAGE_NAME: hello-world

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JFrog CLI
        id: jfrog-setup
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest
          oidc-provider-name: ${{ env.OIDC_PROVIDER_NAME }}
      - name: Log in to JFrog Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ env.JF_URL }}
          username: ${{ steps.jfrog-setup.outputs.oidc-user }}
          password: ${{ steps.jfrog-setup.outputs.oidc-token }}

      - name: Build and push Docker Image
        if: true
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.JF_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
    
      - name: Attach BuildInfo to Docker Image
        id: build-info
        run: |
          
          echo image {{ steps.build.outputs.imageid }}
          echo metadata {{ steps.build.outputs.metadata }}
          
          # convert output to a format that JFrog CLI can use <tag>@<sha256>
          digest=${{ steps.build.outputs.digest }}
          digest_sha256=$(echo $digest | cut -d ':' -f 2)
          echo "${{ env.JF_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}@$digest_sha256" > image.txt
          
          # add another record to the current build info + publish build properties on the image files
          jf rt build-docker-create ${{ env.JF_DOCKER_REPO }} --image-file image.txt 
      - name: Create build-provenance attestation
        id: provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.JF_DOCKER_REPO }}/${{ env.IMAGE_NAME }}/${{ github.run_number }}/wrong-manifest.json
          subject-digest: ${{ steps.build.outputs.digest }}
          #push-to-registry: true

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.JF_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
          format: 'cyclonedx-json'
          output-file: 'sbom.cyclonedx.json'

      - name: Attest SBOM
        uses: actions/attest-sbom@v2
        with:
          subject-name: ${{ env.JF_DOCKER_REPO }}/${{ env.IMAGE_NAME }}/${{ github.run_number }}/manifest.json
          subject-digest: ${{ steps.build.outputs.digest }}
          sbom-path: 'sbom.cyclonedx.json'
          # push-to-registry: true
  

